name: Lint and Test Charts

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - name: Lint only changed charts
        run: |
          CHANGED_DIRS=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD | grep '^charts/' | cut -d/ -f1-2 | sort -u)
          for chart in $CHANGED_DIRS; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Updating dependencies for $chart"
              helm dependency update "$chart"
          
              echo "Linting $chart"
              helm lint "$chart"
            fi
          done