name: lint.yaml
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: helm-lint
        run: ct lint --all
